### ISSUE TITLE
Add Collada (.dae) support

### ISSUE THREAD

**Issue by PolygonalSun** [BabylonJS/BabylonPolymorph#17]
[COLLADA](https://en.wikipedia.org/wiki/COLLADA) is an interchange file format for interactive 3D applications.

**Tasks**
- [x] Familiarize with COLLADA2GLTF project.
- [x] Investigate ways to incorporate project as an importer to convert COLLADA to the intermediate [Asset3D](https://github.com/BabylonJS/BabylonPolymorph/blob/master/Morphs/Importers/CoreUtils/Shared/Asset3D/cpp/Inc/Asset3D/Asset3D.h) structure. See the [OBJ importer](https://github.com/BabylonJS/BabylonPolymorph/tree/master/Morphs/Importers/Transcoders/Shared/Transcoders/Source/TranscoderOBJ) as an example.
- [x] Implement parser to convert COLLADA to Asset3D using COLLADA2GLTF.

- [ ] Add animation
- [ ] CMake Build
